--<ScriptOptions statementTerminator=";"/>


CREATE TABLE "APP"."TBL_TASK" (
		"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
		"PROJECT_NAME" VARCHAR(50) NOT NULL,
		"DATE" DATE DEFAULT current_date NOT NULL,
		"PHASE" VARCHAR(100),
		"MODULE" VARCHAR(100),
		"ACTIVITY" VARCHAR(100),
		"WORK_PRODUCT" VARCHAR(150),
		"HOUR_SPENT" VARCHAR(10),
		"REMARKS" VARCHAR(200),
		"USER_ID" INTEGER
	);


CREATE table "APP"."TBL_GROUP" (
		"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
		"Group_NAME" VARCHAR(60) not NULL
	);


-- For My sql Migration --
	
CREATE TABLE TBL_TASK (
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, 
	PROJECT_NAME VARCHAR(50) NOT NULL, 
	DATE DATE NOT NULL, 
	PHASE VARCHAR(100), MODULE VARCHAR(100), 
	ACTIVITY VARCHAR(100), WORK_PRODUCT VARCHAR(150), 
	HOUR_SPENT VARCHAR(10), REMARKS VARCHAR(200), USER_ID INTEGER);


CREATE TABLE TBL_GROUP (
		ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
		Group_NAME VARCHAR(60) NOT NULL
	);

CREATE TABLE TBL_PICKLIST(
	ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	OPTION_NAME VARCHAR(150) NOT NULL,
	OPTION_VALUE VARCHAR(150),
	SECTION VARCHAR(100) NOT NULL,
	GROUP_ID INTEGER
	);
	
CREATE TABLE TBL_USER (
		ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
		USER_NAME VARCHAR(100) NOT NULL,
		PASSWORD VARCHAR(100) NOT NULL,
		FULL_NAME VARCHAR(60),
		EMP_ID VARCHAR(10),
		GROUP_ID INTEGER,
		STATUS TINYINT(6) DEFAULT 0
	);
	
	

	
