INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(4,"Others","Project");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(5,"Analysis & Design","Phase");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(6,"Development","Phase");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(7,"DIT","Phase");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(8,"External Testing","Phase");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(9,"Others","Phase");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(10,"SIT","Phase");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(11,"UAT","Phase");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(32,"Data Integrity","Modules");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(33,"Code Clean Up","Modules");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(34,"Training Provider","Modules");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(35,"Training Attendee","Modules");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(36,"Self Study","Modules");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(37,"Test Conducted","Modules");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(38,"Test Attendee","Modules");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(40,"Training Assignment Report","Modules");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(41,"N/A","Modules");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(42,"Analysis - Appln Walkthrough","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(43,"Analysis - Document - Fixing review comments","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(44,"Analysis - Document Preparation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(45,"Analysis - Document Review","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(46,"Analysis - Document Study","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(47,"Analysis - Technical","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(48,"Design - Appln Walkthrough","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(49,"Design - Document - Fixing review comments","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(50,"Design - Document Preparation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(51,"Design - Document Review","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(52,"Design - Document Study","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(53,"Design - Technical","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(54,"DEV - Bug Fixing","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(55,"DEV - Build Creation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(56,"DEV - Checklist Preparation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(57,"DEV - Checklist Review","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(58,"DEV - Code Review","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(59,"DEV - Coding","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(60,"DEV - Config/Change Management","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(61,"DEV - Performance Tuning ","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(62,"DEV - Team Coordination","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(63,"DEV - Training Attend - Project Related","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(64,"DEV - Training Provided - Project Related","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(65,"DEV - Unit Test Case Preparation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(66,"DEV - Unit Test Case Review","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(67,"DEV - Unit Testing","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(68,"DEV/TEST - Bugs Validation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(69,"DEV/TEST - Environment Set up","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(70,"DEV/TEST - Traceability Matrix","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(71,"Meetings - Technical/Functional","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(72,"Others - Idle - No Power","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(73,"Others - Idle - No Work","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(74,"Others - Leave","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(75,"Others - Meetings - Non Project","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(76,"Others - Non-Project Related Tasks","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(77,"Others - Permissions/Breaks","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(78,"Others - Self Study - Non-Project","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(79,"Others - Training Attend - Non Project","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(80,"Others - Training Provided - Non Project","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(81,"PM - Audits - Projects - Auditee - Int./Ext. ","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(82,"PM - Concession","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(83,"PM - Contract Review","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(84,"PM - Estimation Preparation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(85,"PM - Estimation Review","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(86,"PM - Meetings - Customer","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(87,"PM - Meetings - Internal","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(88,"PM - Metrics Report Preparation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(89,"PM - MOM - Customer","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(90,"PM - MOM - Internal","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(91,"PM - Project Planning","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(92,"PM - Release Activities","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(93,"PM - Work Allocation / Scheduling","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(94,"QF - Audit Observations","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(95,"QF - Audits","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(96,"QF - Conduct Audit","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(97,"QF - Quality Facilitation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(98,"TEST - Regression Testing","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(99,"TEST - Retesting","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(100,"TEST - Test Case / Script Execution","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(101,"TEST - Test Case / Script Preparation","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(102,"TEST - Test Case / Script Review","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(103,"TEST - Test Case / Script Rework","Activity");
INSERT INTO TBL_PICKLIST (id,option_name,section)VALUES(104,"TEST - Testing","Activity");

update tbl_picklist set group_id = 1 where group_id is null;