insert into App.tbl_picklist(option_name,section) values ('CIBC_ICAP','Project');
insert into App.tbl_picklist(option_name,section) values ('ICAP_REPORTS','Project');
insert into App.tbl_picklist(option_name,section) values ('RMG - Banking','Project');
insert into App.tbl_picklist(option_name,section) values ('Others','Project');

insert into App.tbl_picklist(option_name,section) values ('Analysis & Design','Phase');
insert into App.tbl_picklist(option_name,section) values ('Development','Phase');
insert into App.tbl_picklist(option_name,section) values ('DIT','Phase');
insert into App.tbl_picklist(option_name,section) values ('External Testing','Phase');
insert into App.tbl_picklist(option_name,section) values ('Others','Phase');
insert into App.tbl_picklist(option_name,section) values ('SIT','Phase');
insert into App.tbl_picklist(option_name,section) values ('UAT','Phase');

insert into App.tbl_picklist(option_name,section) values ('Modules','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR CA 38','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR CA 61','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR CA 67','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR CA 77','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR CA 82','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR CA 83','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR CA 84','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR CA 45','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR CA 87','Modules');
insert into App.tbl_picklist(option_name,section) values ('Pre BBR changes - iCap','Modules');
insert into App.tbl_picklist(option_name,section) values ('BBR - SQR changes','Modules');
insert into App.tbl_picklist(option_name,section) values ('BBR - PLSQL changes','Modules');
insert into App.tbl_picklist(option_name,section) values ('Rel 8.2 ','Modules');
insert into App.tbl_picklist(option_name,section) values ('CR Dynamic Schedule A ','Modules');
insert into App.tbl_picklist(option_name,section) values ('RIL #7','Modules');
insert into App.tbl_picklist(option_name,section) values ('RIL #9','Modules');
insert into App.tbl_picklist(option_name,section) values ('RIL Additional Changes','Modules');
insert into App.tbl_picklist(option_name,section) values ('SB Dashboard YTD changes','Modules');
insert into App.tbl_picklist(option_name,section) values ('SB Dashboard Activity Ranking','Modules');
insert into App.tbl_picklist(option_name,section) values ('Data Integrity','Modules');
insert into App.tbl_picklist(option_name,section) values ('Code Clean Up','Modules');
insert into App.tbl_picklist(option_name,section) values ('Training Provider','Modules');
insert into App.tbl_picklist(option_name,section) values ('Training Attendee','Modules');
insert into App.tbl_picklist(option_name,section) values ('Self Study','Modules');
insert into App.tbl_picklist(option_name,section) values ('Test Conducted','Modules');
insert into App.tbl_picklist(option_name,section) values ('Test Attendee','Modules');
insert into App.tbl_picklist(option_name,section) values ('Training Assignment iCap','Modules');
insert into App.tbl_picklist(option_name,section) values ('Training Assignment Report','Modules');
insert into App.tbl_picklist(option_name,section) values ('N/A','Modules');


insert into App.tbl_picklist(option_name,section) values ('Analysis - Appln Walkthrough','Activity');
insert into App.tbl_picklist(option_name,section) values ('Analysis - Document - Fixing review comments','Activity');
insert into App.tbl_picklist(option_name,section) values ('Analysis - Document Preparation','Activity');
insert into App.tbl_picklist(option_name,section) values ('Analysis - Document Review','Activity');
insert into App.tbl_picklist(option_name,section) values ('Analysis - Document Study','Activity');
insert into App.tbl_picklist(option_name,section) values ('Analysis - Technical','Activity');
insert into App.tbl_picklist(option_name,section) values ('Design - Appln Walkthrough','Activity');
insert into App.tbl_picklist(option_name,section) values ('Design - Document - Fixing review comments','Activity');
insert into App.tbl_picklist(option_name,section) values ('Design - Document Preparation','Activity');
insert into App.tbl_picklist(option_name,section) values ('Design - Document Review','Activity');
insert into App.tbl_picklist(option_name,section) values ('Design - Document Study','Activity');
insert into App.tbl_picklist(option_name,section) values ('Design - Technical','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Bug Fixing','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Build Creation','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Checklist Preparation','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Checklist Review','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Code Review','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Coding','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Config/Change Management','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Performance Tuning ','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Team Coordination','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Training Attend - Project Related','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Training Provided - Project Related','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Unit Test Case Preparation','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Unit Test Case Review','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV - Unit Testing','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV/TEST - Bugs Validation','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV/TEST - Environment Set up','Activity');
insert into App.tbl_picklist(option_name,section) values ('DEV/TEST - Traceability Matrix','Activity');
insert into App.tbl_picklist(option_name,section) values ('Meetings - Technical/Functional','Activity');
insert into App.tbl_picklist(option_name,section) values ('Others - Idle - No Power','Activity');
insert into App.tbl_picklist(option_name,section) values ('Others - Idle - No Work','Activity');
insert into App.tbl_picklist(option_name,section) values ('Others - Leave','Activity');
insert into App.tbl_picklist(option_name,section) values ('Others - Meetings - Non Project','Activity');
insert into App.tbl_picklist(option_name,section) values ('Others - Non-Project Related Tasks','Activity');
insert into App.tbl_picklist(option_name,section) values ('Others - Permissions/Breaks','Activity');
insert into App.tbl_picklist(option_name,section) values ('Others - Self Study - Non-Project','Activity');
insert into App.tbl_picklist(option_name,section) values ('Others - Training Attend - Non Project','Activity');
insert into App.tbl_picklist(option_name,section) values ('Others - Training Provided - Non Project','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Audits - Projects - Auditee - Int./Ext. ','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Concession','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Contract Review','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Estimation Preparation','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Estimation Review','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Meetings - Customer','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Meetings - Internal','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Metrics Report Preparation','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - MOM - Customer','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - MOM - Internal','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Project Planning','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Release Activities','Activity');
insert into App.tbl_picklist(option_name,section) values ('PM - Work Allocation / Scheduling','Activity');
insert into App.tbl_picklist(option_name,section) values ('QF - Audit Observations','Activity');
insert into App.tbl_picklist(option_name,section) values ('QF - Audits','Activity');
insert into App.tbl_picklist(option_name,section) values ('QF - Conduct Audit','Activity');
insert into App.tbl_picklist(option_name,section) values ('QF - Quality Facilitation','Activity');
insert into App.tbl_picklist(option_name,section) values ('TEST - Regression Testing','Activity');
insert into App.tbl_picklist(option_name,section) values ('TEST - Retesting','Activity');
insert into App.tbl_picklist(option_name,section) values ('TEST - Test Case / Script Execution','Activity');
insert into App.tbl_picklist(option_name,section) values ('TEST - Test Case / Script Preparation','Activity');
insert into App.tbl_picklist(option_name,section) values ('TEST - Test Case / Script Review','Activity');
insert into App.tbl_picklist(option_name,section) values ('TEST - Test Case / Script Rework','Activity');
insert into App.tbl_picklist(option_name,section) values ('TEST - Testing','Activity');